spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restful_recommend?useSSL=false
    username: root
    password: betty391427
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: collect-microservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8085
